### ISSUE TITLE
Missing `stdgates.inc` in `ir.source` causing crashes with Qiskit QASM3

### ISSUE THREAD

**Issue by contra-bit** [amazon-braket/Braket.jl#100]
**Describe the bug**  
The output of `ir.source` is missing the `stdgates.inc` file, which defines many common gates such as   `cx`, `h`, and `x`. When attempting to import the output of `ir(circuit).status` using `qiskit.qasm3.loads`, the qiskit  crashes because the gate `h` is not recognized as part of the OpenQASM 3 standard. Instead, it is defined in the standard gate library, leading to compatibility issues.

**To reproduce**  
1. Create a quantum circuit that includes the gates `x`  and `h`.
2. Generate the intermediate representation (IR) of the circuit.
3. Copy the output of `ir(circuit).source`.
4. Use `qiskit.qasm3.loads` to import the  qasm output.
5. Observe the crash due to the unrecognized gate `h`.

**Expected behavior**  
I expected the output of `ir(circuit).source` to be successfully imported using `qiskit.qasm3.loads` without any crashes. The gates defined in `stdgates.inc` should be recognized, allowing for seamless integration with the qiskit OpenQASM 3 implementation.

![image](https://github.com/user-attachments/assets/534e4c88-ba5c-4b88-b4da-6d8e751aa39d)

**Screenshots or logs**  
![image](https://github.com/user-attachments/assets/1c9e124b-5713-47e2-a01d-5a0d3809b098)

**System information**  
- **Julia version**: 1.10
- **Braket.jl version**: Main Branch

**Additional context**  
This issue may affect users who rely on the standard gate library for their quantum circuits and expect compatibility with Qiskit and OpenQASM 3. It is crucial to ensure that all standard gates are properly defined and included in the IR output to prevent crashes and improve usability.

**Comment by kshyatt-aws** [comment]
Hi @contra-bit , the reason for this is that Braket uses a different gate library than the standard one (since we have device specific gates) that Qiskit builds off of. If you need the `include stdgates.inc;` line, you can probably insert it into the OQ3 source with a `replace` or similar.
