### ISSUE TITLE
Feature request: support for loading pickled results from Hybrid Jobs

### ISSUE THREAD

**Issue by kshyatt-aws** [amazon-braket/Braket.jl#18]
**Describe the feature you'd like**
Amazon Braket Hybrid Jobs may encapsulate job results in a Python pickle file, especially if the results are large or contain images. Currently Julia isn't able to natively read pickle files (e.g. without shelling out to Python or using PythonCall.jl). Ideally we'd be able to un-pickle these files without any dependency on Python.

**Is this feature already present in the Python SDK?**
[Yes, there is support for pickled results files.](https://github.com/aws/amazon-braket-sdk-python/blob/92b90015be335f543de199272a79f8bc73a38af3/src/braket/jobs/serialization.py)

**How would this feature be used? Please describe.**
Users would be able to extract their results without having to use or install Python.

**Describe alternatives you've considered**
You can currently use pickle either via the shell (e.g. running a `cmd`) or PythonCall, but this isn't ideal behavior.

**Additional context**
There are some nascent pure Julia packages for un-pickling (e.g. [Pandas.jl](https://github.com/JuliaPy/Pandas.jl) and [Pickle.jl](https://github.com/chengchingwen/Pickle.jl)). Any implementation of this feature should explain why a particular package was chosen.

**Comment by WingCode** [comment]
I would like to submit my PR for this issue.
