### ISSUE TITLE
Full support for local detuning

### ISSUE THREAD

**Issue by kshyatt-aws** [amazon-braket/Braket.jl#79]
**Describe the feature you'd like**
QuEra's Aquila [now supports](https://aws.amazon.com/blogs/quantum-computing/local-detuning-now-available-on-queras-aquila-device-with-braket-direct) local detuning with Braket Direct. The underlying structs are implemented in `Braket.jl` but many of the correctness tests and validations are not.

**Is this feature already present in the Python SDK?**
Yes. https://github.com/amazon-braket/amazon-braket-sdk-python/blob/6c4282e7eafcff906c4cfc6804bf06209d82a4fc/src/braket/ahs/local_detuning.py#L23

**How would this feature be used? Please describe.**
Local detuning would be used with Braket Direct to access this advanced feature of Aquila.

**Describe alternatives you've considered**

**Additional context**

**Comment by Fe-r-oz** [comment]
This is interesting! You have already implemented useful underlying structs! I am delighted to work on this!

**Comment by Fe-r-oz** [comment]
Hi, @kshyatt-aws 

Please let me know is this the right track? Thanks

```
julia> magnitude1 = Field(TimeSeries(OrderedDict([0 => TimeSeriesItem(0, 1), 1 => TimeSeriesItem(1, 4)]), true, -1))
Field(TimeSeries(OrderedDict{Number, TimeSeriesItem}(0 => TimeSeriesItem(0, 1), 1 => TimeSeriesItem(1, 4)), true, -1), nothing)

julia> local_detuning1 = LocalDetuning(magnitude1)
LocalDetuning(Field(TimeSeries(OrderedDict{Number, TimeSeriesItem}(0 => TimeSeriesItem(0, 1), 1 => TimeSeriesItem(1, 4)), true, -1), nothing))
```

**Comment by kshyatt-aws** [comment]
Hello,

Looks like a good start. Keep in mind you'll need to be able to `discretize` as well! You can likely find inspiration for tests over at [the Python SDK](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/d5dfbf40182f1858a2cf5db56962daf2e5e57cc3/test/unit_tests/braket/ahs/test_local_detuning.py).

**Comment by Fe-r-oz** [comment]
Indeed. I have also added and tested the `stitch` function from the [the Python SDK](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/d5dfbf40182f1858a2cf5db56962daf2e5e57cc3/test/unit_tests/braket/ahs/test_local_detuning.py). as well! I used the same parameters as used in that test!

```
julia> stitched_ld = stitch(s1, s2, :mean)
LocalDetuning(Field(TimeSeries(OrderedCollections.OrderedDict{Number, TimeSeriesItem}(0.0 => TimeSeriesItem(0.0, 0.75), 0.1 => TimeSeriesItem(0.1, 0.8), 0.2 => TimeSeriesItem(0.2, 0.9), 0.3 => TimeSeriesItem(0.3, 1.0)), true, 1), Pattern(Number[0.3, 0.7, 0.6, -0.5, 0.0, 1.6])))

julia> stitched_ld = stitch(s1, s2, :left)
LocalDetuning(Field(TimeSeries(OrderedCollections.OrderedDict{Number, TimeSeriesItem}(0.0 => TimeSeriesItem(0.3, 1.0), 0.1 => TimeSeriesItem(0.1, 0.8), 0.2 => TimeSeriesItem(0.2, 0.9), 0.3 => TimeSeriesItem(0.3, 1.0)), true, 1), Pattern(Number[0.3, 0.7, 0.6, -0.5, 0.0, 1.6])))

julia> stitched_ld = stitch(s1, s2, :right)
LocalDetuning(Field(TimeSeries(OrderedCollections.OrderedDict{Number, TimeSeriesItem}(0.0 => TimeSeriesItem(0.0, 0.5), 0.1 => TimeSeriesItem(0.1, 0.8), 0.2 => TimeSeriesItem(0.2, 0.9), 0.3 => TimeSeriesItem(0.3, 1.0)), true, 1), Pattern(Number[0.3, 0.7, 0.6, -0.5, 0.0, 1.6])))
```


I can't access `rydberg` from `DiscretizationProperties`. I have this `discretize `function for` local detuning` but I am not sure how I would call the rydberg property like 

`function discretize(ld::LocalDetuning, properties::DiscretizationProperties)`

```
julia> discretize(local_detuning1, Braket.DiscretizationProperties.rydberg)
ERROR: type DataType has no field rydberg
Stacktrace:
 [1] getproperty(x::Type, f::Symbol)
   @ Base ./Base.jl:32
 [2] top-level scope
   @ REPL[32]:1
```

```
julia> Braket.DiscretizationProperties.rydberg
ERROR: type DataType has no field rydberg
Stacktrace:
 [1] getproperty(x::Type, f::Symbol)
   @ Base ./Base.jl:32
 [2] top-level scope
   @ REPL[31]:1
```

Please let me know how to call it properly. Thanks!

**Comment by Fe-r-oz** [comment]
I looked at the` test/ahs.jl.` It seems when testing, we use `MockAhsParadigmProperties`

https://github.com/amazon-braket/Braket.jl/blob/1d05da02807487a83a0f83dc88272ceda3d54465/test/ahs.jl#L17

`MockAhsParadigmProperties` when passing properties to `discretize `when testing.
