### ISSUE TITLE
Support for Braket Direct reservations

### ISSUE THREAD

**Issue by kshyatt-aws** [amazon-braket/Braket.jl#80]
**Describe the feature you'd like**
Amazon Braket now has the [Braket Direct feature](https://docs.aws.amazon.com/braket/latest/developerguide/braket-reservations.html), which allows users to reserve certain Direct-only devices or access experimental capabilities of devices.

**Is this feature already present in the Python SDK?**
Yes. https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/src/braket/aws/direct_reservations.py

**How would this feature be used? Please describe.**
 This allows users to provide a reservation arn to access their reservation, as in the BDK.

**Describe alternatives you've considered**

**Additional context**

**Comment by Fe-r-oz** [comment]
This seem interesting! We need to define DirectReservations in `aws/Device.jl `. We have `AwsDevice`,` Device` here but I am not sure about `AbstractContextManager`. It seems to be imported from

`from contextlib import AbstractContextManager`

But I am not sure what's the equivalent of `AbstractContextManager`  here. Please let me know! Thanks

 There is a lot of Mock Tests about DirectReservations  in [test_direct_reservations.py](https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/test/unit_tests/braket/aws/test_direct_reservations.py)
