### ISSUE TITLE
Support for symbolic expressions in FreeParameters

### ISSUE THREAD

**Issue by kshyatt-aws** [amazon-braket/Braket.jl#82]
**Describe the feature you'd like**
Currently only numerical values are allowed for `FreeParameter`. We should replicate the Python SDK support for `FreeParameterExpression`, allowing gates like `Rx( 2 * alpha /3)`, for example.

**Is this feature already present in the Python SDK?**
Yes. https://github.com/amazon-braket/amazon-braket-sdk-python/blob/main/src/braket/parametric/free_parameter_expression.py

**How would this feature be used? Please describe.**
This would allow more complex expressions for parametrized gates.

**Describe alternatives you've considered**
Currently users have to create new parameters to capture cases like `2 * alpha`.

**Additional context**
An appropriate Julia package should be chosen for the symbolic expressions. `SymbolicExpressions.jl` is one example.

**Comment by kshyatt-aws** [comment]
Yes, I think that would make sense, because `FreeParameterExpression` might contain one or multiple `FreeParameter`s (e.g. `Rx(alpha + 2*beta)`).

**Comment by Fe-r-oz** [comment]
Hi, @kshyatt-aws,

Please let me know that the output looks something like this:

I have used α + 2θ as FreeParameterExpression

```
julia> new_circ = circ(theta=2.0, alpha=1.0)
T  : |    0     |   1   |   2   |Result Types|
                                              
q0 : -H----------Ry(2.0)-Ry(2.0)-Probability--
                                 |            
q1 : -Rx(α + 2θ)-----------------Probability--
                                              
T  : |    0     |   1   |   2   |Result Types|
```

I was spending time with reading the guidelines. Shall I open a PR now?

**Comment by Fe-r-oz** [comment]
Hi, @kshyatt-aws, Please assign the issue to me after closing it! 😬  All suggestion changed have been completed 🙏🏼 !

**Comment by Fe-r-oz** [comment]
Hi, Please assign the closed issue. Thanks.
